# Académies avec emails validés (générée par validate_emails.py)
# Validé le 2026-05-21 22:09:06
# 68 institutions, 199 emails valides

ACADEMIES = [
    {"short": "TRB_NAS", "name": "Transportation Research Board (TRB) - National Academies of Sciences, Engineering, and Medicine", "country": "United States", "emails": ['trb@nas.edu', 'meetings@nas.edu', 'webinars@nas.edu', 'studies@nas.edu', 'annualmeeting@nas.edu', 'cooperativehighwayresearch@nas.edu']},
    {"short": "WMU", "name": "World Maritime University (WMU) - International Maritime Organization (IMO / UN System)", "country": "Sweden", "emails": ['info@wmu.se', 'admissions@wmu.se', 'communications@wmu.se', 'rector@wmu.se', 'registry@wmu.se', 'research@wmu.se']},
    {"short": "AFT_IFTIM_AFTRAL", "name": "AFT-IFTIM / AFTRAL (Apprendre et se Former en Transport et Logistique)", "country": "France", "emails": ['international@aftral.com', 'info@aftral.com', 'partenariats@aftral.com', 'direction@aftral.com', 'communication@aftral.com', 'entreprise@aftral.com']},
    {"short": "CERTH_HIT", "name": "Centre for Research and Technology Hellas - Hellenic Institute of Transport (CERTH-HIT)", "country": "Greece", "emails": ['hit@certh.gr', 'certh@certh.gr', 'research@certh.gr', 'projects@certh.gr', 'partnerships@certh.gr', 'info@certh.gr']},
    {"short": "MIT_CTL", "name": "MIT Center for Transportation & Logistics (MIT CTL)", "country": "United States", "emails": ['ctl-communications@mit.edu', 'ctl-info@mit.edu', 'execed@mit.edu', 'scm-info@mit.edu']},
    {"short": "TTI", "name": "Texas A&M Transportation Institute (TTI)", "country": "United States", "emails": ['tti-info@tti.tamu.edu', 'communications@tti.tamu.edu', 'research@tti.tamu.edu', 'events@tti.tamu.edu']},
    {"short": "CTR_Austin", "name": "Center for Transportation Research - University of Texas at Austin (CTR)", "country": "United States", "emails": ['ctr-info@austin.utexas.edu', 'ctr@utexas.edu']},
    {"short": "NUTC", "name": "Northwestern University Transportation Center (NUTC)", "country": "United States", "emails": ['tcinfo@northwestern.edu', 'transportation@northwestern.edu', 'execed@northwestern.edu']},
    {"short": "CILT_International", "name": "Chartered Institute of Logistics and Transport International (CILT International)", "country": "United Kingdom", "emails": ['info@ciltinternational.org', 'membership@ciltinternational.org', 'events@ciltinternational.org', 'communications@ciltinternational.org']},
    {"short": "UCL_PEARL", "name": "UCL PEARL - University College London", "country": "United Kingdom", "emails": ['pearl@ucl.ac.uk', 'engineering@ucl.ac.uk', 'transport@ucl.ac.uk', 'partnerships@ucl.ac.uk']},
    {"short": "ITS_Leeds", "name": "Institute for Transport Studies - University of Leeds (ITS Leeds)", "country": "United Kingdom", "emails": ['admissions@its.leeds.ac.uk', 'info@its.leeds.ac.uk', 'research@its.leeds.ac.uk', 'business@its.leeds.ac.uk']},
    {"short": "TU_Delft", "name": "Delft University of Technology - Transport & Planning (TU Delft)", "country": "Netherlands", "emails": ['secretary-tp-citg@tudelft.nl', 'citg@tudelft.nl', 'transport@tudelft.nl', 'internationaloffice@tudelft.nl']},
    {"short": "Erasmus_MEL", "name": "Erasmus University Rotterdam - Maritime Economics & Logistics (MEL)", "country": "Netherlands", "emails": ['mel@ese.eur.nl', 'executiveeducation@ese.eur.nl']},
    {"short": "KLU", "name": "Kühne Logistics University (KLU)", "country": "Germany", "emails": ['info@the-klu.org', 'admissions@klu.org', 'executiveeducation@klu.org', 'corporate@klu.org']},
    {"short": "Gustave_Eiffel_SPLOTT", "name": "Université Gustave Eiffel - SPLOTT Laboratory", "country": "France", "emails": ['splott@univ-eiffel.fr', 'recherche@univ-eiffel.fr', 'relations.internationales@univ-eiffel.fr']},
    {"short": "CRET_LOG", "name": "CRET-LOG - Aix-Marseille Université", "country": "France", "emails": ['cret-log@univ-amu.fr', 'contact@cret-log.com', 'recherche@univ-amu.fr']},
    {"short": "LCL_Luxembourg", "name": "Luxembourg Centre for Logistics (LCL)", "country": "Luxembourg", "emails": ['lcl@uni.lu', 'logistics@uni.lu', 'partnerships@uni.lu', 'research@uni.lu']},
    {"short": "ZLC", "name": "Zaragoza Logistics Center (ZLC)", "country": "Spain", "emails": ['info@zlc.edu.es', 'admissions@zlc.edu.es', 'executive.education@zlc.edu.es', 'research@zlc.edu.es']},
    {"short": "IESE_CIIL", "name": "IESE Business School - Center for International Industrial Logistics (CIIL)", "country": "Spain", "emails": ['ciil@iese.edu', 'info@iese.edu', 'executiveeducation@iese.edu', 'corporate@iese.edu']},
    {"short": "CIRRELT", "name": "Interuniversity Research Centre on Enterprise Networks, Logistics and Transportation (CIRRELT)", "country": "Canada", "emails": ['info@cirrelt.ca', 'direction@cirrelt.ca', 'recherche@cirrelt.ca', 'partenariats@cirrelt.ca']},
    {"short": "TLI_AP_NUS", "name": "The Logistics Institute - Asia Pacific (TLI-AP, NUS)", "country": "Singapore", "emails": ['tliinfo@nus.edu.sg', 'tlisg@nus.edu.sg', 'execed@nus.edu.sg', 'partnerships@nus.edu.sg']},
    {"short": "BJTU", "name": "Beijing Jiaotong University (BJTU)", "country": "China", "emails": ['bjtubao@bjtu.edu.cn', 'international@bjtu.edu.cn', 'admissions@bjtu.edu.cn', 'research@bjtu.edu.cn']},
    {"short": "KMOU_ITLS", "name": "Korea Maritime & Ocean University (KMOU) - ITLS", "country": "South Korea", "emails": ['webmaster@kmou.ac.kr', 'international@kmou.ac.kr', 'graduate@kmou.ac.kr', 'research@kmou.ac.kr']},
    {"short": "MISI", "name": "Malaysia Institute for Supply Chain Innovation (MISI)", "country": "Malaysia", "emails": ['info@misi.edu.my', 'admissions@misi.edu.my', 'executiveeducation@misi.edu.my', 'corporate@misi.edu.my']},
    {"short": "ITLS_Sydney", "name": "Institute of Transport and Logistics Studies - University of Sydney (ITLS)", "country": "Australia", "emails": ['business.itlsinfo@sydney.edu.au', 'itlsinfo@sydney.edu.au', 'research.itls@sydney.edu.au']},
    {"short": "RMIT", "name": "RMIT University - Global Transport & Logistics Group", "country": "Australia", "emails": ['transport.logistics@rmit.edu.au', 'industry@rmit.edu.au', 'research@rmit.edu.au']},
    {"short": "ITLI_AASTMT", "name": "International Transport & Logistics Institute - AASTMT (ITLI)", "country": "Egypt", "emails": ['itli@aast.edu', 'info@aast.edu', 'international@aast.edu', 'logistics@aast.edu']},
    {"short": "UM6P", "name": "Mohammed VI Polytechnic University (UM6P) - Sustainable Logistics & Territories Chair", "country": "Morocco", "emails": ['contact@um6p.ma', 'research@um6p.ma', 'international@um6p.ma', 'partnerships@um6p.ma']},
    {"short": "ITF_OECD", "name": "International Transport Forum (ITF/OECD)", "country": "France", "emails": ['itf.contact@itf-oecd.org', 'events@itf-oecd.org', 'outreach@itf-oecd.org']},
    {"short": "IRU", "name": "International Road Transport Union (IRU)", "country": "Switzerland", "emails": ['iru@iru.org', 'communications@iru.org', 'events@iru.org', 'advocacy@iru.org']},
    {"short": "IAPH", "name": "International Association of Ports and Harbors (IAPH)", "country": "Japan", "emails": ['info@iaphworldports.org', 'communications@iaphworldports.org', 'membership@iaphworldports.org']},
    {"short": "UITP", "name": "UITP - International Association of Public Transport", "country": "Belgium", "emails": ['info@uitp.org', 'events@uitp.org', 'media@uitp.org']},
    {"short": "UIC", "name": "UIC - International Union of Railways", "country": "France", "emails": ['mail@uic.org', 'freight@uic.org', 'communications@uic.org']},
    {"short": "SFC", "name": "Smart Freight Centre (SFC)", "country": "Netherlands", "emails": ['info@smartfreightcentre.org', 'partnerships@smartfreightcentre.org', 'communications@smartfreightcentre.org']},
    {"short": "Maersk_Moller_ZeroCarbon", "name": "Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping", "country": "Denmark", "emails": ['info@zerocarbonshipping.com', 'partnerships@zerocarbonshipping.com']},
    {"short": "Fraunhofer_IML", "name": "Fraunhofer Institute for Material Flow and Logistics (IML)", "country": "Germany", "emails": ['info@iml.fraunhofer.de', 'logistics@iml.fraunhofer.de', 'presse@iml.fraunhofer.de']},
    {"short": "DLR", "name": "DLR - German Aerospace Center (Institute of Transport Research)", "country": "Germany", "emails": ['verkehr@dlr.de', 'info@dlr.de', 'presse@dlr.de']},
    {"short": "TRL", "name": "Transport Research Laboratory (TRL)", "country": "United Kingdom", "emails": ['enquiries@trl.co.uk', 'consulting@trl.co.uk', 'innovation@trl.co.uk']},
    {"short": "ASTAR_IHPC", "name": "A*STAR Institute of High Performance Computing (IHPC)", "country": "Singapore", "emails": ['contact@ihpc.a-star.edu.sg', 'partnerships@a-star.edu.sg']},
    {"short": "NYU_Marron", "name": "NYU Marron Institute - Urban Freight Lab", "country": "United States", "emails": ['marron.institute@nyu.edu', 'urbanfreightlab@uw.edu']},
    {"short": "CSRF", "name": "Centre for Sustainable Road Freight (CSRF)", "country": "United Kingdom", "emails": ['info@csrf.ac.uk', 'partnerships@csrf.ac.uk']},
    {"short": "Chalmers", "name": "Chalmers University of Technology - Shipping & Marine Technology", "country": "Sweden", "emails": ['shipping@chalmers.se', 'maritime@chalmers.se']},
    {"short": "KRRI", "name": "Korea Railroad Research Institute (KRRI)", "country": "South Korea", "emails": ['krri@krri.re.kr', 'international@krri.re.kr', 'global@krri.re.kr']},
    {"short": "RTRI", "name": "Railway Technical Research Institute (RTRI)", "country": "Japan", "emails": ['plan@rtri.or.jp', 'international@rtri.or.jp']},
    {"short": "CARS", "name": "China Academy of Railway Sciences (CARS)", "country": "China", "emails": ['cars@rails.cn', 'international@rails.cn']},
    {"short": "Victoria_SupplyChain", "name": "Institute of Supply Chain and Logistics - Victoria University", "country": "Australia", "emails": ['logistics@vu.edu.au', 'partnerships@vu.edu.au']},
    {"short": "Antwerp_PortInnovation", "name": "Port Innovation Lab - Antwerp-Bruges", "country": "Belgium", "emails": ['info@portofantwerpbruges.com', 'innovation@portofantwerpbruges.com']},
    {"short": "SMI_Singapore", "name": "Singapore Maritime Institute (SMI)", "country": "Singapore", "emails": ['info@maritimeinstitute.sg', 'research@maritimeinstitute.sg']},
    {"short": "NLA_Nordic", "name": "Nordic Logistics Association (NLA)", "country": "Norway", "emails": ['post@nla.no', 'logistics@nla.no']},
    {"short": "ETH_Zurich_IVT", "name": "ETH Zurich - Institute for Transport Planning and Systems", "country": "Switzerland", "emails": ['info@ivt.baug.ethz.ch', 'research@ivt.baug.ethz.ch']},
    {"short": "PIANC", "name": "PIANC - World Association for Waterborne Transport Infrastructure", "country": "Belgium", "emails": ['info@pianc.org', 'secretary.general@pianc.org']},
    {"short": "UNECE_ITC", "name": "Inland Transport Committee (UNECE)", "country": "Switzerland", "emails": ['inland.transport@un.org', 'unece@un.org']},
    {"short": "WAPPP", "name": "World Association of PPP Units & Professionals (WAPPP)", "country": "Switzerland", "emails": ['secretariat@wapp.network', 'events@wapp.network']},
    {"short": "GCMD", "name": "Global Centre for Maritime Decarbonisation (GCMD)", "country": "Singapore", "emails": ['info@gcformd.org', 'partnerships@gcformd.org']},
    {"short": "ERTICO", "name": "ERTICO - ITS Europe", "country": "Belgium", "emails": ['info@mail.ertico.com', 'events@mail.ertico.com']},
    {"short": "OpenLogistics_Found", "name": "Open Logistics Foundation", "country": "Germany", "emails": ['info@openlogisticsfoundation.org', 'community@openlogisticsfoundation.org']},
    {"short": "ALICE", "name": "ALICE - Alliance for Logistics Innovation through Collaboration in Europe", "country": "Belgium", "emails": ['info@etp-alice.eu', 'secretariat@etp-alice.eu']},
    {"short": "IMB_Maglev", "name": "International Maglev Board (IMB)", "country": "Switzerland", "emails": ['office@maglevboard.net']},
    {"short": "ERRAC", "name": "European Rail Research Advisory Council (ERRAC)", "country": "Belgium", "emails": ['info@errac.org', 'secretariat@errac.org']},
    {"short": "Shift2Rail", "name": "Shift2Rail / Europe's Rail Joint Undertaking", "country": "Belgium", "emails": ['info@rail-research.europa.eu']},
    {"short": "AAPA", "name": "American Association of Port Authorities (AAPA)", "country": "United States", "emails": ['info@aapa-ports.org', 'membership@aapa-ports.org']},
    {"short": "CAR_Automotive", "name": "Center for Automotive Research (CAR)", "country": "United States", "emails": ['info@cargroup.org', 'communications@cargroup.org']},
    {"short": "MPA_Academy", "name": "Maritime and Port Authority of Singapore Academy (MPA Academy)", "country": "Singapore", "emails": ['mpa_academy@mpa.gov.sg', 'academy@mpa.gov.sg']},
    {"short": "ITS_America", "name": "Intelligent Transportation Society of America (ITS America)", "country": "United States", "emails": ['info@itsa.org', 'events@itsa.org']},
    {"short": "JIFFA_Academy", "name": "Japan International Freight Forwarders Association (JIFFA)", "country": "Japan", "emails": ['soumu@jiffa.or.jp', 'jiffa@jiffa.or.jp']},
    {"short": "CIS_Shipbrokers", "name": "Chartered Institute of Shipbrokers (CIS)", "country": "United Kingdom", "emails": ['membership@cis.org.uk', 'education@cis.org.uk']},
    {"short": "PortXL_Rotterdam", "name": "Port of Rotterdam Authority - PortXL Innovation Hub", "country": "Netherlands", "emails": ['info@portxl.org', 'innovation@portofrotterdam.com']},
    {"short": "Dubai_Future", "name": "Dubai Future Foundation - Dubai Sandbox / Mobility Programs", "country": "United Arab Emirates", "emails": ['info@dubaifuture.ae']},

    # ── BATCH 2 — 40 nouvelles institutions de prestige (2026-05-29) ──
    {"short": "Harvard_BSCM",      "name": "Harvard Business School - Global Supply Chain",                                          "country": "United States",  "emails": ["research@hbs.edu", "cpd@hbs.edu"]},
    {"short": "Wharton_OID",       "name": "Wharton School - Operations, Information & Decisions Dept.",                            "country": "United States",  "emails": ["wharton@wharton.upenn.edu"]},
    {"short": "Oxford_TSU",        "name": "University of Oxford - Transport Studies Unit",                                          "country": "United Kingdom", "emails": ["enquiries@tsu.ox.ac.uk"]},
    {"short": "Cambridge_CSIC",    "name": "University of Cambridge - Centre for Smart Infrastructure & Construction",               "country": "United Kingdom", "emails": ["csic-admin@eng.cam.ac.uk"]},
    {"short": "INSEAD_SCM",        "name": "INSEAD - Supply Chain Management Programme",                                             "country": "France",         "emails": ["research@insead.edu"]},
    {"short": "HEC_ISOM",          "name": "HEC Paris - Dept. of Information Systems & Operations Management",                      "country": "France",         "emails": ["research@hec.fr"]},
    {"short": "GeorgiaTech_SCL",   "name": "Georgia Tech Supply Chain and Logistics Institute",                                      "country": "United States",  "emails": ["course@scl.gatech.edu"]},
    {"short": "TUM_TSE",           "name": "TU Munich - Chair of Transportation Systems Engineering",                                "country": "Germany",        "emails": ["webcommunications@tum.de"]},
    {"short": "TUWien_Transport",  "name": "TU Wien - Institute of Transportation",                                                  "country": "Austria",        "emails": ["fvv.office@tuwien.ac.at"]},
    {"short": "KAIST_Mobility",    "name": "KAIST - Mobility Group",                                                                 "country": "South Korea",    "emails": ["info@kaist.ac.kr"]},
    {"short": "StellenboschU_LOG", "name": "Stellenbosch University - Department of Logistics",                                      "country": "South Africa",   "emails": ["jacquin@sun.ac.za"]},
    {"short": "Shanghai_SMU",      "name": "Shanghai Maritime University - International Office",                                    "country": "China",          "emails": ["iec@shmtu.edu.cn"]},
    {"short": "Tsinghua_SIGS_LOG", "name": "Tsinghua University Shenzhen - Division of Logistics & Transportation",                 "country": "China",          "emails": ["ieoffice@tsinghua.edu.cn"]},
    {"short": "UNCTAD_TL",         "name": "UNCTAD - Trade Logistics Branch",                                                        "country": "Switzerland",    "emails": ["unctad-tf@un.org", "jan.hoffmann@unctad.org"]},
    {"short": "IMO",               "name": "International Maritime Organization",                                                    "country": "United Kingdom", "emails": ["info@imo.org", "maritimeknowledgecentre@imo.org"]},
    {"short": "UN_Habitat_Mob",    "name": "UN-Habitat - Mobility and Transport Unit",                                               "country": "Kenya",          "emails": ["infohabitat@unhabitat.org"]},
    {"short": "ECA_TICID",         "name": "UN Economic Commission for Africa - Technology, Infrastructure & Connectivity",          "country": "Ethiopia",       "emails": ["eca-info@un.org"]},
    {"short": "ESCWA_CTL",         "name": "UN ESCWA - Committee on Transport and Logistics",                                        "country": "Lebanon",        "emails": ["escwa-info@un.org"]},
    {"short": "WTO_TF",            "name": "World Trade Organization - Trade Facilitation Division",                                 "country": "Switzerland",    "emails": ["enquiries@wto.org"]},
    {"short": "IsDB_Infra",        "name": "Islamic Development Bank - Infrastructure & Transport Division",                         "country": "Saudi Arabia",   "emails": ["info@isdb.org"]},
    {"short": "RAND_Transport",    "name": "RAND Corporation - Transportation Research Division",                                     "country": "United States",  "emails": ["external_affairs@rand.org"]},
    {"short": "WEF_SCT",           "name": "World Economic Forum - Supply Chain & Transportation Community",                         "country": "Switzerland",    "emails": ["contact@weforum.org"]},
    {"short": "GIZ_Transport",     "name": "GIZ - Deutsche Gesellschaft fuer Internationale Zusammenarbeit (Sustainable Transport)", "country": "Germany",        "emails": ["info@giz.de"]},
    {"short": "Brookings_Metro",   "name": "Brookings Institution - Metropolitan Policy Program (Transport)",                        "country": "United States",  "emails": ["metro@brookings.edu"]},
    {"short": "HPA_Hamburg",       "name": "Hamburg Port Authority (HPA)",                                                           "country": "Germany",        "emails": ["info@hpa.hamburg.de"]},
    # TangerMed_PA — exclu volontairement (contact direct préféré)
    {"short": "MAWANI_Saudi",      "name": "Saudi Ports Authority (MAWANI)",                                                         "country": "Saudi Arabia",   "emails": ["info@mawani.gov.sa"]},
    {"short": "TNPA_Durban",       "name": "Transnet National Ports Authority - Port of Durban",                                     "country": "South Africa",   "emails": ["customercare.tnpa@transnet.net"]},
    {"short": "AUDA_NEPAD",        "name": "African Union Development Agency (AUDA-NEPAD) - Infrastructure & Transport",            "country": "South Africa",   "emails": ["info@nepad.org"]},
    {"short": "AU_Transport",      "name": "African Union Commission - Directorate of Transport and Mobility",                       "country": "Ethiopia",       "emails": ["au-info@africa-union.org"]},
    {"short": "KAUST_Mobility",    "name": "King Abdullah University of Science & Technology - Future Mobility Sandbox",            "country": "Saudi Arabia",   "emails": ["support@kaust.edu.sa"]},
    {"short": "AfDB_Transport",    "name": "African Development Bank - Infrastructure & Urban Development",                          "country": "Ivory Coast",    "emails": ["afdb@afdb.org"]},
    {"short": "IATA_Cargo",        "name": "International Air Transport Association (IATA) - Cargo & Multimodal",                   "country": "Canada",         "emails": ["iata@iata.org"]},
    {"short": "ACI_World",         "name": "Airports Council International - ACI World",                                             "country": "Canada",         "emails": ["aci@aci.aero"]},
    {"short": "DHL_Innovation",    "name": "DHL - Innovation Center (Logistics Trend Radar)",                                        "country": "Germany",        "emails": ["amic@dhl.com"]},
    {"short": "MIT_Mobility",      "name": "MIT - Mobility Future Initiative (MMI)",                                                 "country": "United States",  "emails": ["mobility-future@mit.edu"]},
    {"short": "GlobeTrade_ITC",    "name": "International Trade Centre (ITC/WTO-UNCTAD)",                                           "country": "Switzerland",    "emails": ["itcnews@intracen.org"]},
    {"short": "FIATA",             "name": "FIATA - International Federation of Freight Forwarders Associations",                   "country": "Switzerland",    "emails": ["info@fiata.org"]},
    {"short": "IRF_Roads",         "name": "International Road Federation (IRF)",                                                    "country": "Switzerland",    "emails": ["info@irfnet.ch"]},
    {"short": "CSCMP",             "name": "Council of Supply Chain Management Professionals (CSCMP)",                              "country": "United States",  "emails": ["cscmpinfo@cscmp.org"]},

    # ── BATCH 3 — USA / Europe / Australia (2026-05-29) ──
    {"short": "UCLA_ITS",         "name": "UCLA Institute of Transportation Studies",                                                          "country": "United States",  "emails": ["its@ucla.edu"]},
    {"short": "UMTRI",            "name": "University of Michigan Transportation Research Institute (UMTRI)",                                  "country": "United States",  "emails": ["umtri@umich.edu"]},
    {"short": "Stanford_GSCMF",   "name": "Stanford Graduate School of Business - Global Supply Chain Management Forum",                       "country": "United States",  "emails": ["gsb_info@gsb.stanford.edu"]},
    {"short": "Purdue_GSCMI",     "name": "Purdue University - Global Supply Chain Management Initiative (GSCMI)",                             "country": "United States",  "emails": ["gscmi@purdue.edu"]},
    {"short": "ASU_WPCarey_SCM",  "name": "Arizona State University - W. P. Carey School of Business, Supply Chain Management",               "country": "United States",  "emails": ["scm@asu.edu"]},
    {"short": "PSU_LTI",          "name": "Penn State - Thomas D. Larson Pennsylvania Transportation Institute",                               "country": "United States",  "emails": ["lti@psu.edu"]},
    {"short": "USDOT_Volpe",      "name": "Volpe National Transportation Systems Center (USDOT)",                                             "country": "United States",  "emails": ["askvolpe@dot.gov"]},
    {"short": "ATRI",             "name": "American Transportation Research Institute (ATRI)",                                                 "country": "United States",  "emails": ["atri@trucking.org"]},
    {"short": "UTRC_CCNY",        "name": "University Transportation Research Center (UTRC) - City College of New York",                      "country": "United States",  "emails": ["ethor@utrc2.org"]},
    {"short": "UArk_SCMRC",       "name": "University of Arkansas - Supply Chain Management Research Center, Walton College",                  "country": "United States",  "emails": ["scmrc@walton.uark.edu"]},
    {"short": "OSU_Fisher_SCM",   "name": "Ohio State University - Master of Supply Chain Management, Fisher College",                         "country": "United States",  "emails": ["mscm@fisher.osu.edu"]},
    {"short": "TAMU_ReadCenter",  "name": "Texas A&M - Global Supply Chain Lab & Read Center for Distribution Research",                      "country": "United States",  "emails": ["readcenter@tamu.edu"]},
    {"short": "Imperial_TSC",     "name": "Imperial College London - Transport Strategy Centre (TSC)",                                         "country": "United Kingdom", "emails": ["enquiries.tsc@imperial.ac.uk"]},
    {"short": "Cranfield_LOG",    "name": "Cranfield University - Centre for Logistics, Procurement and Supply Chain Management",              "country": "United Kingdom", "emails": ["info@cranfield.ac.uk"]},
    {"short": "Southampton_SMMI", "name": "University of Southampton - Southampton Marine and Maritime Institute (SMMI)",                      "country": "United Kingdom", "emails": ["smmi@southampton.ac.uk"]},
    {"short": "Edinburgh_IIE",    "name": "University of Edinburgh - Institute for Infrastructure and Environment (IIE)",                      "country": "United Kingdom", "emails": ["RIS.Eng@ed.ac.uk"]},
    {"short": "ENPC_LVMT",        "name": "Ecole des Ponts ParisTech - LVMT Laboratoire Ville Mobilite Transport",                            "country": "France",         "emails": ["gestion-lvmt@liste.enpc.fr"]},
    {"short": "RWTH_ISB",         "name": "RWTH Aachen University - Chair and Institute of Urban and Transport Planning (ISB)",               "country": "Germany",        "emails": ["institut@isb.rwth-aachen.de"]},
    {"short": "KIT_IfV",          "name": "Karlsruhe Institute of Technology (KIT) - Institute for Transport Studies (IfV)",                  "country": "Germany",        "emails": ["info@ifv.kit.edu"]},
    {"short": "UHamburg_IVW",     "name": "University of Hamburg - Institute of Transport Economics (IVW)",                                   "country": "Germany",        "emails": ["bwl.info@uni-hamburg.de"]},
    {"short": "POLIMI_MIP_SCM",   "name": "Politecnico di Milano - MIP Graduate School of Management, Digital Supply Chain",                  "country": "Italy",          "emails": ["info@mip.polimi.it"]},
    {"short": "SDA_Bocconi",      "name": "SDA Bocconi School of Management - Operations & Supply Chain",                                     "country": "Italy",          "emails": ["info@sdabocconi.it"]},
    {"short": "KTH_CTS",          "name": "KTH Royal Institute of Technology - Centre for Transport Studies (CTS)",                           "country": "Sweden",         "emails": ["cts-info@kth.se"]},
    {"short": "DTU_Transport",    "name": "Technical University of Denmark (DTU) - Division of Transportation Science",                       "country": "Denmark",        "emails": ["dtu@dtu.dk"]},
    {"short": "Aalto_IEM_Log",    "name": "Aalto University - Department of Industrial Engineering and Management, Logistics Research",       "country": "Finland",        "emails": ["registry@aalto.fi"]},
    {"short": "KULeuven_iTL",     "name": "KU Leuven - Innovative Technology for Logistics (iTL)",                                            "country": "Belgium",        "emails": ["litl@kuleuven.be"]},
    {"short": "IST_CERIS",        "name": "IST Lisbon - CERIS Civil Engineering Research and Innovation for Sustainability (Transport)",      "country": "Portugal",       "emails": ["ceris@tecnico.ulisboa.pt"]},
    {"short": "FEUP_Porto",       "name": "University of Porto - Faculty of Engineering (FEUP), Transport & Logistics",                       "country": "Portugal",       "emails": ["feup@fe.up.pt"]},
    {"short": "WUT_Transport",    "name": "Warsaw University of Technology - Faculty of Transport",                                           "country": "Poland",         "emails": ["dziekan.wt@pw.edu.pl"]},
    {"short": "UMelbourne_Infra", "name": "University of Melbourne - Department of Infrastructure Engineering, Transport Group",              "country": "Australia",      "emails": ["infrastructure-eng@unimelb.edu.au"]},
    {"short": "Monash_ITS",       "name": "Monash University - Institute of Transport Studies (ITS)",                                         "country": "Australia",      "emails": ["itsinfo@monash.edu"]},
    {"short": "QUT_STRC",         "name": "Queensland University of Technology - Smart Transport Research Centre (STRC)",                     "country": "Australia",      "emails": ["strc@qut.edu.au"]},
    {"short": "Austroads",        "name": "Austroads - Australian Road and Transport Research Association",                                    "country": "Australia",      "emails": ["info@austroads.com.au"]},
    {"short": "InfraAustralia",   "name": "Infrastructure Australia",                                                                         "country": "Australia",      "emails": ["mail@infrastructureaustralia.gov.au"]},
    {"short": "BITRE",            "name": "BITRE - Bureau of Infrastructure and Transport Research Economics (Australian Government)",        "country": "Australia",      "emails": ["bitre@infrastructure.gov.au"]},

    # ── BATCH 4 — USA, Canada, Europe, Australie (mai 2026) ──────────────
    # ── USA ──────────────────────────────────────────────────────────────
    {"short": "TRB_NatAcad",      "name": "Transportation Research Board (TRB) — National Academies of Sciences",         "country": "United States",  "emails": ["trr@nas.edu"]},
    {"short": "AAPA_Ports",       "name": "American Association of Port Authorities (AAPA)",                               "country": "United States",  "emails": ["info@aapa-ports.org"]},
    {"short": "ASCM",             "name": "ASCM — Association for Supply Chain Management (formerly APICS)",               "country": "United States",  "emails": ["support@ascm.org"]},
    {"short": "Eno_Transport",    "name": "Eno Center for Transportation — Washington DC",                                 "country": "United States",  "emails": ["publicaffairs@enotrans.org"]},
    {"short": "NUTC_NW",          "name": "Northwestern University Transportation Center (NUTC)",                          "country": "United States",  "emails": ["TCinfo@northwestern.edu"]},

    # ── CANADA ───────────────────────────────────────────────────────────
    {"short": "CILTNA",           "name": "Chartered Institute of Logistics & Transport — North America (CILTNA)",         "country": "Canada",         "emails": ["admin@ciltna.com"]},
    {"short": "UBC_Sauder_OL",    "name": "University of British Columbia — Sauder School, Operations & Logistics",       "country": "Canada",         "emails": ["oplog@sauder.ubc.ca"]},
    {"short": "McMaster_DSB",     "name": "McMaster University — DeGroote School of Business, Operations Management",     "country": "Canada",         "emails": ["dsbdean@mcmaster.ca"]},
    {"short": "UToronto_Rotman",  "name": "University of Toronto — Rotman Commerce, Supply Chain Management",             "country": "Canada",         "emails": ["rotmancommerce.info@utoronto.ca"]},
    {"short": "PortVancouver",    "name": "Vancouver Fraser Port Authority — Port of Vancouver",                           "country": "Canada",         "emails": ["info@portvancouver.com"]},

    # ── EUROPE — UNITED KINGDOM ──────────────────────────────────────────
    {"short": "Logistics_UK",     "name": "Logistics UK — UK Road Freight & Logistics Association",                       "country": "United Kingdom", "emails": ["consultingandstandards@logistics.org.uk"]},
    {"short": "UCL_CTS",          "name": "University College London — Centre for Transport Studies (CTS)",               "country": "United Kingdom", "emails": ["transport-institute@ucl.ac.uk"]},
    {"short": "Leeds_ITS",        "name": "University of Leeds — Institute for Transport Studies (ITS)",                  "country": "United Kingdom", "emails": ["info@its.leeds.ac.uk"]},

    # ── EUROPE — FRANCE / SUISSE ─────────────────────────────────────────
    # ITF_OECD already in batch 1 (line 34)
    {"short": "IRU_Geneva",       "name": "IRU — International Road Transport Union, Geneva",                             "country": "Switzerland",    "emails": ["iru@iru.org"]},
    {"short": "UIC_Paris",        "name": "UIC — International Union of Railways (Union Internationale des Chemins de fer)", "country": "France",      "emails": ["contact@uic.org"]},

    # ── EUROPE — NETHERLANDS ─────────────────────────────────────────────
    {"short": "TUDelft_TP",       "name": "TU Delft — Department of Transport & Planning (Faculty CEG)",                  "country": "Netherlands",    "emails": ["secr-tp-citg@tudelft.nl"]},
    {"short": "RSM_Erasmus",      "name": "Erasmus University Rotterdam — Rotterdam School of Management (RSM), SCM",     "country": "Netherlands",    "emails": ["info@rsm.nl"]},

    # ── EUROPE — BELGIUM ─────────────────────────────────────────────────
    {"short": "ELA_Logistics",    "name": "ELA — European Logistics Association, Brussels",                               "country": "Belgium",        "emails": ["office@elalog.eu"]},
    {"short": "CLECAT",           "name": "CLECAT — European Association for Forwarding, Transport & Customs Services",   "country": "Belgium",        "emails": ["info@clecat.org"]},
    {"short": "AMS_LogSCM",       "name": "Antwerp Management School — Global Supply Chain & Logistics",                  "country": "Belgium",        "emails": ["info@antwerpmanagementschool.be"]},
    {"short": "UAntwerp_TPR",     "name": "University of Antwerp — Dept. of Transport & Regional Economics (TPR)",        "country": "Belgium",        "emails": ["departement.tpr@uantwerpen.be"]},
    {"short": "ESC_Shippers",     "name": "ESC — European Shippers' Council, Brussels",                                   "country": "Belgium",        "emails": ["k.kliuyeva@europeanshippers.eu"]},

    # ── EUROPE — NORDIQUES ───────────────────────────────────────────────
    {"short": "CBS_OpMgmt",       "name": "Copenhagen Business School (CBS) — Department of Operations Management",       "country": "Denmark",        "emails": ["yg.om@cbs.dk"]},
    {"short": "VTI_Sweden",       "name": "VTI — Swedish National Road and Transport Research Institute",                 "country": "Sweden",         "emails": ["nordic@vti.se"]},
    {"short": "Chalmers_SCM",     "name": "Chalmers University of Technology — Supply Chain Management (Gothenburg)",     "country": "Sweden",         "emails": ["kontakt@chalmers.se"]},

    # ── AUSTRALIE ────────────────────────────────────────────────────────
    {"short": "SCLAA",            "name": "SCLAA — Supply Chain & Logistics Association of Australia",                    "country": "Australia",      "emails": ["secretary@sclaa.com.au"]},
    {"short": "PortsAustralia",   "name": "Ports Australia — Peak Body Australian Port Industry",                         "country": "Australia",      "emails": ["info@portsaustralia.com.au"]},
    {"short": "USydney_ITLS",     "name": "University of Sydney — Institute of Transport & Logistics Studies (ITLS)",     "country": "Australia",      "emails": ["business.itls@sydney.edu.au"]},
    {"short": "RMIT_Maritime",    "name": "RMIT University — Australian Maritime Logistics Research Network",             "country": "Australia",      "emails": ["vinh.thai@rmit.edu.au"]},

    # ── BATCH 5 — Fédérations, Associations & Académies (mai 2026) ───────
    # ── Fédérations Internationales ──────────────────────────────────────
    {"short": "GSF",              "name": "Global Shippers Forum (GSF)",                                                       "country": "United Kingdom", "emails": ["secretariat@globalshippersforum.com"]},
    {"short": "TIACA",            "name": "The International Air Cargo Association (TIACA)",                                   "country": "Canada",         "emails": ["info@tiaca.org"]},
    {"short": "ALACAT",           "name": "ALACAT — Federación Agentes de Carga América Latina y el Caribe",                   "country": "Colombia",       "emails": ["coordinacion@alacat.org"]},
    {"short": "ICHCA",            "name": "ICHCA — International Cargo Handling Coordination Association",                     "country": "United Kingdom", "emails": ["admin@ichca.com"]},
    {"short": "WCAworld",         "name": "WCA World Cargo Alliance Network",                                                  "country": "Hong Kong",      "emails": ["info@wcaworld.com"]},
    {"short": "AFFA_ASEAN",       "name": "AFFA — ASEAN Federation of Forwarders Associations",                                "country": "Indonesia",      "emails": ["affasecretariat@gmail.com"]},
    {"short": "ICS_Shipping",     "name": "International Chamber of Shipping (ICS)",                                           "country": "United Kingdom", "emails": ["ics@ics-shipping.org"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "IAPH",             "name": "International Association of Ports and Harbors (IAPH)",                             "country": "Japan",          "emails": ["info@iaphworldports.org"]},
    # ── Europe ───────────────────────────────────────────────────────────
    {"short": "UnionTLF",         "name": "Union TLF — Entreprises de Transport et de Logistique de France",                  "country": "France",         "emails": ["tlf@e-tlf.com"]},
    {"short": "DSLV",             "name": "DSLV — Deutscher Speditions- und Logistikverband",                                 "country": "Germany",        "emails": ["info@dslv.spediteure.de"]},
    {"short": "Confetra",         "name": "Confetra — Confederazione Generale italiana dei Trasporti e della Logistica",      "country": "Italy",          "emails": ["confetra@confetra.com"]},
    {"short": "Febetra",          "name": "Febetra — Fédération Royale Belge des Transporteurs & Logistiques",               "country": "Belgium",        "emails": ["info@febetra.be"]},
    {"short": "TLN_NL",           "name": "TLN — Transport en Logistiek Nederland",                                           "country": "Netherlands",    "emails": ["info@tln.nl"]},
    {"short": "SPEDLOGSWISS",     "name": "SPEDLOGSWISS — Verband Schweizerischer Speditions- und Logistikunternehmen",       "country": "Switzerland",    "emails": ["info@spedlogswiss.com"]},
    {"short": "ASTIC",            "name": "ASTIC — Asociación de Transporte Internacional por Carretera (Spain)",             "country": "Spain",          "emails": ["info@astic.net"]},
    {"short": "OFGE",             "name": "OFGE — Hellenic Federation of International Freight Forwarders & Logistics",       "country": "Greece",         "emails": ["info@ofge.gr"]},
    {"short": "PISIL",            "name": "PISIL — Polska Izba Spedycji i Logistyki",                                         "country": "Poland",         "emails": ["pisil@pisil.pl"]},
    {"short": "UTIKAD",           "name": "UTIKAD — Uluslararası Taşımacılık ve Lojistik Hizmet Üretenleri Derneği",         "country": "Turkey",         "emails": ["info@utikad.org.tr"]},
    # ── Amériques ────────────────────────────────────────────────────────
    {"short": "ATA_Trucking",     "name": "ATA — American Trucking Associations",                                              "country": "United States",  "emails": ["info@trucking.org"]},
    {"short": "CIFFA",            "name": "CIFFA — Canadian International Freight Forwarding Association",                    "country": "Canada",         "emails": ["info@ciffa.com"]},
    {"short": "NTC_Brasil",       "name": "NTC & Logística — Associação Nacional do Transporte de Cargas e Logística",        "country": "Brazil",         "emails": ["ntc@ntc.org.br"]},
    {"short": "AMACARGA",         "name": "AMACARGA — Asociación Mexicana de Agentes de Carga",                               "country": "Mexico",         "emails": ["direccion@amacarga.mx"]},
    {"short": "FITAC",            "name": "FITAC — Federación Colombiana de Logística, Carga y Comercio Exterior",            "country": "Colombia",       "emails": ["info@fitac.net"]},
    {"short": "AAACI",            "name": "AAACI — Asociación Argentina de Agentes de Carga Internacional",                   "country": "Argentina",      "emails": ["info@aaaci.org.ar"]},
    {"short": "ALOG_Chile",       "name": "ALOG Chile — Asociación Logística de Chile A.G.",                                  "country": "Chile",          "emails": ["info@alog.cl"]},
    # ── Asie-Pacifique ───────────────────────────────────────────────────
    {"short": "ALC_Australia",    "name": "ALC — Australian Logistics Council",                                                "country": "Australia",      "emails": ["admin@austlogistics.com.au"]},
    {"short": "CIFA",             "name": "CIFA — China International Freight Forwarders Association",                        "country": "China",          "emails": ["cifa@cifa.org.cn"]},
    {"short": "JIFFA",            "name": "JIFFA — Japan International Freight Forwarders Association",                       "country": "Japan",          "emails": ["info@jiffa.or.jp"]},
    {"short": "KIFFA_Korea",      "name": "KIFFA — Korea International Freight Forwarders Association",                       "country": "South Korea",    "emails": ["kiffa@kiffa.or.kr"]},
    {"short": "FFFAI",            "name": "FFFAI — Federation of Freight Forwarders' Associations in India",                  "country": "India",          "emails": ["info@fffai.org"]},
    {"short": "SLA_Singapore",    "name": "SLA — Singapore Logistics Association",                                             "country": "Singapore",      "emails": ["slamail@sla.org.sg"]},
    {"short": "FMFF",             "name": "FMFF — Federation of Malaysian Freight Forwarders",                                "country": "Malaysia",       "emails": ["secretariat@fmff.net"]},
    {"short": "TIFFA",            "name": "TIFFA — Thai International Freight Forwarders Association",                        "country": "Thailand",       "emails": ["center@tiffathai.org"]},
    {"short": "VLA",              "name": "VLA — Vietnam Logistics Business Association",                                      "country": "Vietnam",        "emails": ["vla-hcm@vla.com.vn"]},
    {"short": "PIFFA",            "name": "PIFFA — Pakistan International Freight Forwarders Association",                    "country": "Pakistan",       "emails": ["piffa@piffa.com"]},
    {"short": "HAFFA",            "name": "HAFFA — Hong Kong Association of Freight Forwarding & Logistics",                  "country": "Hong Kong",      "emails": ["enquiry@haffa.com.hk"]},
    {"short": "AFPI",             "name": "AFPI — Association of Freight Forwarders of the Philippines",                      "country": "Philippines",    "emails": ["secretary_general@afpi.org.ph"]},
    {"short": "ALFI",             "name": "ALFI — Asosiasi Logistik dan Forwarder Indonesia",                                 "country": "Indonesia",      "emails": ["sekretariat@alfi.or.id"]},
    # ── Moyen-Orient & Afrique ───────────────────────────────────────────
    {"short": "SALA",             "name": "SALA — Saudi Logistics Association",                                                "country": "Saudi Arabia",   "emails": ["info@sala.sa"]},
    {"short": "NAFL",             "name": "NAFL — National Association of Freight and Logistics (UAE)",                       "country": "UAE",            "emails": ["info@nafl.ae"]},
    {"short": "QatarChamber_Log", "name": "Qatar Chamber — Logistics Committee",                                               "country": "Qatar",          "emails": ["info@qcci.org"]},
    {"short": "OLA_Oman",         "name": "OLA — Oman Logistics Association",                                                  "country": "Oman",           "emails": ["ola@ola.om"]},
    {"short": "KSC_Kuwait",       "name": "KSC — Kuwait Shipping Companies & Agents Association",                              "country": "Kuwait",         "emails": ["info@kscaa.org"]},
    {"short": "JLA_Jordan",       "name": "JLA — Jordan Logistics Association",                                                "country": "Jordan",         "emails": ["info@jla.jo"]},
    {"short": "LFS_Lebanon",      "name": "LFS — Lebanese Forwarders Syndicate",                                               "country": "Lebanon",        "emails": ["info@lfs-lb.org"]},
    {"short": "ADOLOG",           "name": "ADOLOG — Asociación Dominicana de Operadores Logísticos",                          "country": "Dominican Rep.", "emails": ["info@adolog.org.do"]},
    {"short": "EIFFA",            "name": "EIFFA — Egyptian International Freight Forwarding Association",                    "country": "Egypt",          "emails": ["info@eiffa.com"]},
    {"short": "KIFWA",            "name": "KIFWA — Kenya International Freight Forwarding & Warehousing Association",          "country": "Kenya",          "emails": ["info@kifwa.co.ke"]},
    {"short": "ANLCA",            "name": "ANLCA — Association of Nigerian Licensed Customs Agents",                           "country": "Nigeria",        "emails": ["secretariat@anlca.org.ng"]},
    {"short": "GIFF",             "name": "GIFF — Ghana Institute of Freight Forwarders",                                     "country": "Ghana",          "emails": ["giff@giff.org.gh"]},
    # ── Académies & Centres de recherche ─────────────────────────────────
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "MIT_CTL",          "name": "MIT Center for Transportation & Logistics (MIT CTL)",                              "country": "United States",  "emails": ["ctl-communications@mit.edu"]},
    {"short": "TTI_TAMU",         "name": "Texas A&M Transportation Institute (TTI)",                                         "country": "United States",  "emails": ["tti-info@tti.tamu.edu"]},
    {"short": "CTR_UTAustin",     "name": "Center for Transportation Research — University of Texas at Austin (CTR)",         "country": "United States",  "emails": ["ctr-info@austin.utexas.edu"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "NYU_Marron",       "name": "NYU Marron Institute — Urban Freight Lab",                                         "country": "United States",  "emails": ["marron.institute@nyu.edu"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "ITS_America",      "name": "Intelligent Transportation Society of America (ITS America)",                      "country": "United States",  "emails": ["info@itsa.org"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "CIRRELT",          "name": "CIRRELT — Interuniversity Research Centre on Enterprise Networks, Logistics and Transportation", "country": "Canada", "emails": ["info@cirrelt.ca"]},
    {"short": "CILT_Intl",        "name": "CILT International — Chartered Institute of Logistics and Transport",              "country": "United Kingdom", "emails": ["info@ciltinternational.org"]},
    {"short": "TRL_UK",           "name": "TRL — Transport Research Laboratory",                                              "country": "United Kingdom", "emails": ["enquiries@trl.co.uk"]},
    {"short": "CSRF_UK",          "name": "CSRF — Centre for Sustainable Road Freight",                                       "country": "United Kingdom", "emails": ["info@csrf.ac.uk"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "CIS_Shipbrokers",  "name": "Chartered Institute of Shipbrokers (CIS)",                                         "country": "United Kingdom", "emails": ["membership@cis.org.uk"]},
    {"short": "AFTRAL",           "name": "AFTRAL (AFT-IFTIM) — Apprendre et se Former en Transport et Logistique",          "country": "France",         "emails": ["international@aftral.com"]},
    {"short": "GustaveEiffel_SCM","name": "Université Gustave Eiffel — SPLOTT Laboratory (Transport & Logistics)",            "country": "France",         "emails": ["splott@univ-eiffel.fr"]},
    {"short": "CRETLOG_AMU",      "name": "CRET-LOG — Aix-Marseille Université, Centre de Recherche en Transport et Logistique", "country": "France",      "emails": ["cret-log@univ-amu.fr"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "KLU",              "name": "Kühne Logistics University (KLU) — Hamburg",                                       "country": "Germany",        "emails": ["info@the-klu.org"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "Fraunhofer_IML",   "name": "Fraunhofer Institute for Material Flow and Logistics (IML)",                       "country": "Germany",        "emails": ["info@iml.fraunhofer.de"]},
    {"short": "DLR_Transport",    "name": "DLR — German Aerospace Center, Institute of Transport Research",                   "country": "Germany",        "emails": ["verkehr@dlr.de"]},
    {"short": "OpenLogistics",    "name": "Open Logistics Foundation",                                                        "country": "Germany",        "emails": ["info@openlogisticsfoundation.org"]},
    {"short": "MEL_Erasmus",      "name": "Erasmus University Rotterdam — Maritime Economics & Logistics (MEL)",              "country": "Netherlands",    "emails": ["info@meloffice.nl"]},
    {"short": "SmartFreight",     "name": "Smart Freight Centre (SFC)",                                                       "country": "Netherlands",    "emails": ["info@smartfreightcentre.org"]},
    {"short": "PortXL_Rot",       "name": "Port of Rotterdam — PortXL Innovation Hub",                                        "country": "Netherlands",    "emails": ["info@portxl.org"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "UITP",             "name": "UITP — International Association of Public Transport, Brussels",                   "country": "Belgium",        "emails": ["info@uitp.org"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "ERTICO",           "name": "ERTICO — ITS Europe, Brussels",                                                    "country": "Belgium",        "emails": ["info@mail.ertico.com"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "PIANC",            "name": "PIANC — World Association for Waterborne Transport Infrastructure",                 "country": "Belgium",        "emails": ["info@pianc.org"]},
    {"short": "PortAntwerp_Innov","name": "Port of Antwerp-Bruges — Innovation Lab",                                          "country": "Belgium",        "emails": ["innovation@portofantwerpbruges.com"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "ERRAC",            "name": "ERRAC — European Rail Research Advisory Council",                                   "country": "Belgium",        "emails": ["info@errac.org"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "Shift2Rail",       "name": "Shift2Rail / Europe's Rail Joint Undertaking",                                     "country": "Belgium",        "emails": ["info@rail-research.europa.eu"]},
    {"short": "ETH_IVT",          "name": "ETH Zurich — Institute for Transport Planning and Systems (IVT)",                  "country": "Switzerland",    "emails": ["info@ivt.baug.ethz.ch"]},
    {"short": "MaerskZeroCarbon", "name": "Maersk Mc-Kinney Moller Center for Zero Carbon Shipping",                         "country": "Denmark",        "emails": ["info@zerocarbonshipping.com"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "NLA_Nordic",       "name": "NLA — Nordic Logistics Association",                                               "country": "Norway",         "emails": ["post@nla.no"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "CERTH_HIT",        "name": "CERTH-HIT — Hellenic Institute of Transport",                                      "country": "Greece",         "emails": ["hit@certh.gr"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "LCL_Luxembourg",   "name": "Luxembourg Centre for Logistics (LCL) — University of Luxembourg",                 "country": "Luxembourg",     "emails": ["lcl@uni.lu"]},
    {"short": "ZLC_Zaragoza",     "name": "Zaragoza Logistics Center (ZLC)",                                                   "country": "Spain",          "emails": ["info@zlc.edu.es"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "IESE_CIIL",        "name": "IESE Business School — Center for International Industrial Logistics (CIIL)",       "country": "Spain",          "emails": ["ciil@iese.edu"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "WMU",              "name": "World Maritime University (WMU) — IMO / UN System",                                "country": "Sweden",         "emails": ["info@wmu.se"]},
    {"short": "TLI_NUS",          "name": "The Logistics Institute Asia Pacific (TLI-AP) — NUS Singapore",                    "country": "Singapore",      "emails": ["tliinfo@nus.edu.sg"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "BJTU",             "name": "Beijing Jiaotong University (BJTU) — Logistics & Transport",                       "country": "China",          "emails": ["international@bjtu.edu.cn"]},
    {"short": "KMOU",             "name": "Korea Maritime & Ocean University (KMOU) — ITLS",                                  "country": "South Korea",    "emails": ["international@kmou.ac.kr"]},
    {"short": "MISI_Malaysia",    "name": "Malaysia Institute for Supply Chain Innovation (MISI)",                             "country": "Malaysia",       "emails": ["info@misi.edu.my"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "SMI_Singapore",    "name": "Singapore Maritime Institute (SMI)",                                                "country": "Singapore",      "emails": ["info@maritimeinstitute.sg"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "MPA_Academy",      "name": "Maritime and Port Authority of Singapore Academy (MPA Academy)",                   "country": "Singapore",      "emails": ["mpa_academy@mpa.gov.sg"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "KRRI",             "name": "KRRI — Korea Railroad Research Institute",                                          "country": "South Korea",    "emails": ["krri@krri.re.kr"]},
    {"short": "RTRI_Japan",       "name": "RTRI — Railway Technical Research Institute (Japan)",                               "country": "Japan",          "emails": ["plan@rtri.or.jp"]},
    {"short": "VU_SCL",           "name": "Victoria University — Institute of Supply Chain and Logistics",                    "country": "Australia",      "emails": ["logistics@vu.edu.au"]},
    # DUPLICATE REMOVED (already in batch 1/2/3): {"short": "ITLI_AASTMT",      "name": "ITLI — International Transport & Logistics Institute, AASTMT (Egypt)",             "country": "Egypt",          "emails": ["itli@aast.edu"]},
]
